### PR TITLE
Add 24.7 Support

### PR DESCRIPTION
**Pull request by kdhlab**
I think this should be all that is required to make 24.7 work. I couldn't get the molecule tests to run locally so if someone can test, that would be good.

### CODE REVIEW

**Comment by DonGiovanni83** [comment]
Thank you very much for you contribution, it is much appreciated. I will test your changes in the coming days and follow up with any feedback.

**Comment by KiLLuuuhh** [comment]
Hi @kdhlab 
FYI: The molecule tests ran successfully with these changes. We'll discuss further tests for the new version later today.

**Comment by KiLLuuuhh** [comment]
I wrote a little checklist for each module in order to keep track of any eventual changes required:

| module | xml-comparison | release notes | molecule tests | unit tests | mvc app models | no additional config required |
| ------------| -------------------------| --------------------| ----------------------|---------------|--------------|---------------------------------------|
| firewall_rules|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|
| interfaces_assignments |:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|
| system_access_users |:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:|none found |:white_check_mark:|
| system_high_availability_settings | changes detected | no changes mentioned |:white_check_mark:|:white_check_mark:| [changes detected](https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Core/Hasync.xml)| https://github.com/puzzle/puzzle.opnsense/issues/148 |
| system_settings_general |:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:| none found | :white_check_mark:|
| system_settings_logging |:white_check_mark:|:white_check_mark:|:white_check_mark:|:white_check_mark:| none found | :white_check_mark:|

With this checks made, this pull request is currently blocked by https://github.com/puzzle/puzzle.opnsense/issues/148.

**Comment by kdhlab** [comment]
Closing this in favor of #149

**Comment by KiLLuuuhh** [comment]
Dear @kdhlab 

Could you please rebase with d64d7a6e33862539ca30d4431a05e7f8eef29eda? Your pull-request includes all other important changes needed to add compatibility with 24.7.

Again, thank you for your vital contribution!

**Comment by kdhlab** [comment]
@KiLLuuuhh rebased. Let me know if we need anything else.

**Review by rekup — APPROVED** [review]
LGTM

**Pull request merged**
